### ISSUE TITLE
Routing broken

### ISSUE THREAD

**Issue by tobbexiv** [DrivenNetwork/pagekit-listings#1]
I wanted to try this addon out, but if I install pagekit not in the root folder, but in a subfolder (e.g. `example.com/pagekit`) the routing in admin area is mostly broken. You hardcoded most of the admin url calls which makes links like `example.com/admin/listings` instead of `example.com/pagekit/admin/listings`. Thus the addon is not usable for me at the moment. To avoid this you can use the route generator.

If you can fix this I would be happy as the addon sounds linke something I can really use :)

**Comment by luisreyes** [comment]
Didn't think about that at the time. I'll add it soon.
