### ISSUE TITLE
Exposure of personal data

### ISSUE THREAD

**Issue by tobbexiv** [DrivenNetwork/pagekit-listings#10]
Personal data like email, registration date, last login, structure of admin menu, role ids, ... is present in the listing json in the page view. For privacy reasons this should not be the case.

Suggestion: Either remove line [ListingsModule.php#L34](https://github.com/DrivenNetwork/pagekit-listings/blob/master/src/Module/ListingsModule.php#L34) completely (best option in my opinion) or change it to 
```
            ->related(['editor' => function($query) {
                return $query
                    ->select('id', 'username');
            }])
```
Then there is still the keys available, but at least the data ist not presented to everybody.

Also consider if all data which is returned by the other entities is really necessary and adjust the `jsonSerialize` function if possible.

**Comment by luisreyes** [comment]
Ah yes! Incomplete functionality. It'll be cleaned up on the next release. Thanks.

**Comment by luisreyes** [comment]
Resolve in commit 133cd0959337a865d98cbb1700a76360569f7ec2. 
Version is now 1.0.5

**Comment by tobbexiv** [comment]
To me it seems that you fixed the issue in the admin panel, but missed the frontend. The line linked above is still unchanged and I can access the personal data in the frontend after updating. So please re-open this issue.

**Comment by luisreyes** [comment]
Your correct. Thanks for pointing it out. This was very deep and overlooked.
