### ISSUE TITLE
[Templates] Broken due to maximum string length

### ISSUE THREAD

**Issue by tobbexiv** [DrivenNetwork/pagekit-listings#2]
The templates are broken as DBALs string type has a maximum length. This should be converted to "text" instead as text has no maximum length: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#string

**Comment by luisreyes** [comment]
Fixed in https://github.com/DrivenNetwork/pagekit-listings/commit/0742710f2ea3586484c41dca9f6d2701c9965f18
